[build-system]
requires = [ "setuptools>=77", "setuptools-scm",]
build-backend = "setuptools.build_meta"

[project]
name = "arches-vue-components"
version = "2.0.1"
readme = "README.md"
requires-python = ">=3.12"
license = "AGPL-3.0-or-later"
license-files = [ "LICENSE",]
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Framework :: Django",
    "Framework :: Django :: 6.0",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
]
dependencies = [ "arches>=8.0.0", "arches-querysets[drf]<2.0.0,>=1.1.0a0",]
dynamic = []

[[project.authors]]
name = "Arches Project"

[project.urls]
Homepage = "https://archesproject.org/"
Documentation = "https://arches.readthedocs.io"
Repository = "https://github.com/archesproject/arches-vue-components.git"
Issues = "https://github.com/archesproject/arches-vue-components/issues"

[dependency-groups]
dev = [ "black==24.4.2", "coverage", "django-silk==5.4.3", "livereload", "pre-commit==4.5.1", "sst",]

[tool.setuptools]
packages = [ "arches_vue_components",]
